name: 编译 AzerothCore-WoTLK (Windows x64)

on:
  workflow_dispatch:
    inputs:
      coreRepo:
        description: 'AzerothCore核心仓库URL'
        required: true
        default: 'https://github.com/azerothcore/azerothcore-wotlk.git'
      coreBranch:
        description: '核心仓库分支'
        required: true
        default: 'master'
      modules:
        description: '要安装的模块 (格式: 仓库URL:分支，多个用逗号分隔)'
        required: false
        default: 'https://github.com/azerothcore/mod-ah-bot:master,https://github.com/azerothcore/mod-ip-tracker:master'
      buildType:
        description: '编译类型'
        type: choice
        required: true
        default: 'RelWithDebInfo'
        options:
          - Release
          - RelWithDebInfo
          - Debug
      withTests:
        description: '是否编译测试'
        type: boolean
        required: true
        default: false

jobs:
  build:
    runs-on: windows-2022
    timeout-minutes: 120
    name: Windows x64 编译流程

    steps:
      - name: 系统信息
        run: |
          Write-Host "操作系统版本: $([Environment]::OSVersion.VersionString)"
          Write-Host "处理器数量: $($env:NUMBER_OF_PROCESSORS)"
        shell: pwsh

      - name: 安装 Chocolatey 包管理器
        run: |
          Set-ExecutionPolicy Bypass -Scope Process -Force
          [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072
          iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))
        shell: pwsh

      - name: 安装编译依赖 (使用MySQL 8.4.6)
        run: |
          choco install -y cmake --installargs 'ADD_CMAKE_TO_PATH=System'
          choco install -y git
          choco install -y openssl --version 1.1.1q
          choco install -y boost-msvc-14.3 --version 1.81.0.0
          choco install -y mysql --version 8.4.6  # 使用MySQL 8.4.6版本
          choco install -y nlohmann-json
        shell: pwsh

      - name: 验证依赖安装
        run: |
          cmake --version
          git --version
          openssl version
          mysql --version  # 验证MySQL版本是否为8.4.6
        shell: pwsh

      - name: 检出 AzerothCore 核心
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.inputs.coreRepo }}
          ref: ${{ github.event.inputs.coreBranch }}
          path: 'azerothcore'
          submodules: 'recursive'
          fetch-depth: 0

      - name: 安装指定模块
        if: ${{ github.event.inputs.modules != '' }}
        run: |
          $modulesList = "${{ github.event.inputs.modules }}".Split(',')
          $moduleDir = "azerothcore/modules"
          
          if (-not (Test-Path $moduleDir)) {
              New-Item -Path $moduleDir -ItemType Directory -Force | Out-Null
          }
          
          foreach ($module in $modulesList) {
              $module = $module.Trim()
              if ([string]::IsNullOrEmpty($module)) { continue }
              
              $parts = $module.Split(':')
              $repoUrl = $parts[0].Trim()
              $branch = if ($parts.Count -gt 1) { $parts[1].Trim() } else { 'master' }
              
              $moduleName = ($repoUrl -split '/' | Select-Object -Last 1) -replace '\.git$', ''
              $targetPath = "$moduleDir/$moduleName"
              
              Write-Host "安装模块: $moduleName 从 $repoUrl 分支 $branch"
              git clone --branch $branch --depth 1 $repoUrl $targetPath
              
              if (-not (Test-Path $targetPath)) {
                  Write-Error "模块 $moduleName 安装失败"
                  exit 1
              }
          }
        shell: pwsh

      - name: 配置 CMake
        run: |
          $buildType = "${{ github.event.inputs.buildType }}"
          $withTests = ${{ github.event.inputs.withTests }}
          
          New-Item -Path "azerothcore/build" -ItemType Directory -Force | Out-Null
          cd azerothcore/build
          
          $cmakeArgs = @(
              "..",
              "-G", "Visual Studio 17 2022",
              "-A", "x64",
              "-DCMAKE_INSTALL_PREFIX=../env/dist",
              "-DCMAKE_BUILD_TYPE=$buildType",
              "-DBUILD_AZEROTHCORE_TOOLS=ON",
              "-DSCRIPTS=static",
              "-DTOOLS=ON",
              "-DENABLE_MYSQL_CLIENT=ON",
              "-DUSE_SFMT=ON"
          )
          
          if ($withTests) {
              $cmakeArgs += "-DBUILD_TESTING=ON"
          } else {
              $cmakeArgs += "-DBUILD_TESTING=OFF"
          }
          
          cmake $cmakeArgs
        shell: pwsh

      - name: 编译项目
        run: |
          cd azerothcore/build
          msbuild AzerothCore.sln /p:Configuration=${{ github.event.inputs.buildType }} /p:Platform=x64 /maxcpucount /verbosity:minimal
        shell: pwsh

      - name: 安装编译结果
        run: |
          cd azerothcore/build
          msbuild INSTALL.vcxproj /p:Configuration=${{ github.event.inputs.buildType }} /p:Platform=x64 /maxcpucount
        shell: pwsh

      - name: 验证编译结果
        run: |
          $exePath = "azerothcore/env/dist/bin/worldserver.exe"
          if (Test-Path $exePath) {
              Write-Host "编译成功! 找到 worldserver.exe"
              Get-Item $exePath | Select-Object Name, Length, LastWriteTime
          } else {
              Write-Error "编译失败! 未找到 worldserver.exe"
              exit 1
          }
        shell: pwsh

      - name: 打包编译产物
        run: |
          Compress-Archive -Path azerothcore/env/dist/* -DestinationPath azerothcore-${{ github.sha }}-${{ github.event.inputs.buildType }}.zip -Force
        shell: pwsh

      - name: 上传编译产物
        uses: actions/upload-artifact@v3
        with:
          name: azerothcore-windows-x64-${{ github.event.inputs.buildType }}
          path: azerothcore-*.zip
          retention-days: 7
    
