name: 编译AzerothCore（Windows-修复语法错误）

env:
  REPO_URL: "https://github.com/azerothcore/azerothcore-wotlk.git"
  BRANCH: "main"
  INSTALL_DIR: "./install"
  MYSQL_INCLUDE: "C:/Program Files/MySQL/MySQL Connector C++ 8.0/include"
  MYSQL_LIB: "C:/Program Files/MySQL/MySQL Connector C++ 8.0/lib64/vs14/libmysql.lib"
  OPENSSL_DIR: "C:/Program Files/OpenSSL-Win64"

on:
  push:
    branches: [ ${{ env.BRANCH }} ]
  workflow_dispatch:
  schedule:
    - cron: "0 19 * * *"

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: pwsh
        working-directory: ${{ github.workspace }}

    steps:
      - name: 拉取源码及核心子模块
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.repository.full_name }}
          ref: ${{ env.BRANCH }}
          submodules: recursive
          fetch-depth: 0
          clean: true

      - name: 安装编译依赖（修正MySQL包名）
        run: |
          if (Get-Service -Name "MySQL" -ErrorAction SilentlyContinue) {
            Stop-Service -Name "MySQL" -Force
            sc delete MySQL | Out-Null
          }
          choco install -y `
            cmake `
            mysql-connector-cpp --version 8.0.36 `
            openssl --version 1.1.1w `
            zlib `
            --no-progress
          if (-not (Test-Path "${{ env.MYSQL_INCLUDE }}")) {
            Write-Error "MySQL头文件路径不存在：${{ env.MYSQL_INCLUDE }}"
            exit 1
          }
          if (-not (Test-Path "${{ env.MYSQL_LIB }}")) {
            Write-Error "MySQL库文件不存在：${{ env.MYSQL_LIB }}"
            exit 1
          }

      - name: 初始化VS2022 x64编译环境
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64
          toolset: 143

      - name: 生成VS2022解决方案（指定依赖路径）
        run: |
          mkdir -Force build | Out-Null
          cd build
          cmake .. `
            -G "Visual Studio 17 2022" `
            -A x64 `
            -DCMAKE_INSTALL_PREFIX="${{ env.INSTALL_DIR }}" `
            -DCMAKE_BUILD_TYPE=Release `
            -DAC_USE_STD_MALLOC=ON `
            -DENABLE_MYSQL_SSL=ON `
            -DTOOLS_BUILD=ON `
            -DSCRIPTS=static `
            -DMYSQL_INCLUDE_DIR="${{ env.MYSQL_INCLUDE }}" `
            -DMYSQL_LIBRARY="${{ env.MYSQL_LIB }}" `
            -DOPENSSL_ROOT_DIR="${{ env.OPENSSL_DIR }}" `
            -DOPENSSL_INCLUDE_DIR="${{ env.OPENSSL_DIR }}/include" `
            -DOPENSSL_LIBRARIES="${{ env.OPENSSL_DIR }}/lib/libssl.lib;${{ env.OPENSSL_DIR }}/lib/libcrypto.lib"
          if (-not (Test-Path "AzerothCore.sln")) {
            Write-Error "CMake生成解决方案失败，未找到AzerothCore.sln"
            exit 1
          }

      - name: 用MSBuild编译项目
        run: |
          $slnPath = "./build/AzerothCore.sln"
          msbuild $slnPath `
            /p:Configuration=Release `
            /p:Platform=x64 `
            /p:VisualStudioVersion=17.0 `
            /m `
            /nologo `
            /fl:msbuild.log
          if (-not (Test-Path "./build/bin/Release/authserver.exe")) {
            Write-Error "authserver.exe编译失败，未找到文件"
            exit 1
          }
          if (-not (Test-Path "./build/bin/Release/worldserver.exe")) {
            Write-Error "worldserver.exe编译失败，未找到文件"
            exit 1
          }

      - name: 安装编译结果
        run: |
          cd build
          cmake --install . --config Release
          if (-not (Test-Path "${{ env.INSTALL_DIR }}/bin/authserver.exe")) {
            Write-Error "安装失败，未在目标目录找到authserver.exe"
            exit 1
          }

      - name: 压缩编译产物
        run: |
          7z a -tzip "azerothcore-${{ env.BRANCH }}-win64.zip" "${{ env.INSTALL_DIR }}\*"
          if (-not (Test-Path "azerothcore-${{ env.BRANCH }}-win64.zip")) {
            Write-Error "压缩失败，未生成zip包"
            exit 1
          }

      - name: 上传编译结果及日志
        uses: actions/upload-artifact@v4
        with:
          name: azerothcore-${{ env.BRANCH }}-exe
          # 关键修复：将序列格式改为逗号分隔的单个字符串，避免YAML序列解析错误
          path: azerothcore-${{ env.BRANCH }}-win64.zip, ./build/msbuild.log
          retention-days: 14
