name: Build AzerothCore-WoTLK

on:
  workflow_dispatch:
    inputs:
      repo:
        description: 'AzerothCore repository URL'
        required: true
        default: 'azerothcore/azerothcore-wotlk.git'
      branch:
        description: 'Branch to build'
        required: true
        default: 'master'
      modules:
        description: 'Modules to include (separated by |)'
        required: false
        default: ''

jobs:
  build:
    runs-on: windows-latest
    
    env:
      # 基础配置
      AC_REPO: ${{ github.event.inputs.repo }}
      AC_BRANCH: ${{ github.event.inputs.branch }}
      AC_MODULES: ${{ github.event.inputs.modules }}
      
      # 目录设置
      SOURCE_DIR: ${{ github.workspace }}/azerothcore
      BUILD_DIR: ${{ github.workspace }}/build
      INSTALL_DIR: ${{ github.workspace }}/install
      BOOST_VERSION: 1.82.0
      BOOST_INSTALL_DIR: D:\boost  # Boost安装到D盘根目录下的boost文件夹

    steps:
      - name: Checkout AzerothCore
        uses: actions/checkout@v4
        with:
          repository: ${{ env.AC_REPO }}
          ref: ${{ env.AC_BRANCH }}
          path: ${{ env.SOURCE_DIR }}
          submodules: 'recursive'

      - name: Checkout Modules
        if: env.AC_MODULES != ''
        run: |
          $modules = $env:AC_MODULES -split '\|'
          foreach ($module in $modules) {
            $moduleName = $module.Split('/')[-1] -replace '\.git$', ''
            $modulePath = "${{ env.SOURCE_DIR }}\modules\$moduleName"
            Write-Host "Cloning module: $module to $modulePath"
            git clone $module $modulePath
          }
        shell: pwsh

      - name: Install Boost
        run: |
          # 确保D盘Boost安装目录存在
          if (-not (Test-Path "${{ env.BOOST_INSTALL_DIR }}")) {
            New-Item -Path "${{ env.BOOST_INSTALL_DIR }}" -ItemType Directory -Force | Out-Null
            Write-Host "Created Boost install directory: ${{ env.BOOST_INSTALL_DIR }}"
          }

          # 通过Chocolatey安装Boost到D盘指定目录
          Write-Host "Installing Boost ${{ env.BOOST_VERSION }} to ${{ env.BOOST_INSTALL_DIR }}"
          choco install boost-msvc-14.3 --version=${{ env.BOOST_VERSION }} `
            --install-directory="${{ env.BOOST_INSTALL_DIR }}" `
            -y --no-progress

          # 验证安装是否成功
          if (-not (Test-Path "${{ env.BOOST_INSTALL_DIR }}\include")) {
            throw "Boost installation failed - include directory not found"
          }

          # 设置BOOST_ROOT环境变量（指向实际安装路径）
          echo "BOOST_ROOT=${{ env.BOOST_INSTALL_DIR }}" | Out-File -FilePath $env:GITHUB_ENV -Append
          Write-Host "BOOST_ROOT set to: ${{ env.BOOST_INSTALL_DIR }}"
        shell: pwsh

      - name: Configure CMake
        run: |
          mkdir -p ${{ env.BUILD_DIR }}
          cd ${{ env.BUILD_DIR }}
          
          cmake ${{ env.SOURCE_DIR }} `
            -G "Visual Studio 17 2022" `
            -A x64 `
            -DCMAKE_INSTALL_PREFIX="${{ env.INSTALL_DIR }}" `
            -DBOOST_ROOT="${{ env.BOOST_ROOT }}" ` 
            -DTOOLS=1 `
            -DSCRIPTS=1 `
            -DCMAKE_BUILD_TYPE=Release
        shell: pwsh

      - name: Build with MSBuild
        run: |
          cd ${{ env.BUILD_DIR }}
          msbuild AzerothCore.sln /p:Configuration=Release /p:Platform=x64 /m /p:BuildInParallel=true
        shell: pwsh

      - name: Install
        run: |
          cd ${{ env.BUILD_DIR }}
          msbuild INSTALL.vcxproj /p:Configuration=Release /p:Platform=x64 /m
        shell: pwsh

      - name: Package Build
        run: |
          Compress-Archive -Path "${{ env.INSTALL_DIR }}\*" -DestinationPath "${{ github.workspace }}\azerothcore-build.zip"
        shell: pwsh

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: azerothcore-wotlk-build
          path: ${{ github.workspace }}\azerothcore-build.zip
          retention-days: 7
