name: 安装 Boost 1.89.0 (MSVC 14.3 64位)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  install-boost:
    runs-on: windows-latest
    steps:
      - name: 从国内镜像下载 Boost 安装包
        uses: carlosperate/download-file-action@v2
        with:
          file-url: "https://archives.boost.io/release/1.89.0/binaries/boost_1_89_0-msvc-14.3-64.exe"
          file-name: "boost_installer.exe"
          location: "./"

      - name: 静默安装 Boost 到工作目录
        run: |
          .\boost_installer.exe /S /INSTALLDIR="${{ github.workspace }}\boost" /NOICONS
        shell: powershell

      - name: 验证 Boost 安装目录
        run: |
          $boostPath = "${{ github.workspace }}\boost"
          if (Test-Path $boostPath) {
            Write-Host "Boost 安装目录存在：$boostPath"
            Get-ChildItem -Path $boostPath -Recurse | Select-Object -First 10
          } else {
            Write-Error "Boost 安装目录不存在，安装失败！"
            exit 1
          }
        shell: powershell

      - name: 设置 Boost 环境变量
        run: |
          $boostPath = "${{ github.workspace }}\boost"
          echo "BOOST_ROOT=$boostPath" | Out-File -FilePath $env:GITHUB_ENV -Append
          echo "PATH=$env:PATH;$boostPath\lib64-msvc-14.3" | Out-File -FilePath $env:GITHUB_ENV -Append
        shell: powershell
